### ISSUE TITLE
Cannot delete secure cookies

### ISSUE THREAD

**Issue by hex2bit** [stevermeister/ngx-cookie-service#81]
If a cookie is set with the "Secure" flag it cannot be deleted because the delete method does not allow for that parameter to be passed/set.

**Comment by webcourse-ng** [comment]
There's a pull request ready with a patch. Until it's merged, I'm working around it by doing another set instead of delete. Setting a cookie with a name that already exists, matching flags and a past date causes the cookie to self-destruct.

`this.cookieService.set('koala_cookie', '', new Date('Thu, 01 Jan 1970 00:00:01 GMT'), '/', 'www.jungle.koala', true, 'None')`

**Comment by jdussouillez** [comment]
PR with the patch : https://github.com/stevermeister/ngx-cookie-service/pull/79

@stevermeister Do you have a release date for this ?

**Comment by stevermeister** [comment]
it's already published, please use version 3.0.0
