### ISSUE TITLE
Cookie not set without explicit LAX samesite attribute or Secure flag

### ISSUE THREAD

**Issue by axos88** [stevermeister/ngx-cookie-service#98]
## Expected Behavior
Cookie should be set

## Actual Behavior
It's not.

## Steps to Reproduce the Problem
1. Navigate to https://localhost:4200 (Same for http proto, with one differnce, see below) on Google Chrome 80+
2. Set the cookieservice to temp1 variable (Used console.log and then save as temp variable)

a. temp1.set('c', 'b') -> silently(!!) not set
b. temp1.set('c', 'b', undefined, undefined, undefined, true) -> works (only over https ofc)
c. temp1.set('c', 'b', undefined, undefined, undefined, undefined, 'lax') -> works

## Specifications

  - Version: 3.0.0
  - Browser: Chrome 80

**Comment by dsouzadyn** [comment]
Can confirm, I'm having the same issue on 2.3.0. I think it's a chrome thing

**Comment by dsouzadyn** [comment]
Chrome browser version: Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by axos88** [comment]
It's not (only) a chrome thing, firefox also announced they will be changing cookie samesite behaviour.

**Comment by duydnguyen07** [comment]
Seems like setting sameSite to None explicitly will now produce a warning via this PR, https://github.com/stevermeister/ngx-cookie-service/commit/1dc9bf231623eb5d81e85600bb71a46e6e37bafc

And the default value for sameSite for when nothing is specified is now Lax via this PR: https://github.com/stevermeister/ngx-cookie-service/commit/0cb4839f50b7effd1dee9abe64e4110363f44ccb

Not much else to do but to upgrade to latest version and always forcefully set your sameSite option. I didnt do it, and now my previous releases will no longer work in new browsers.

**Comment by dsouzadyn** [comment]
Cool, we could close issue, this is a breaking change tho. Hope people know about this.

**Comment by stadler** [comment]
I guess the problem ist that if SameSite is not set through the API it will explicitly set to SameSite=None. This was fine until Chrome v80. But now the Chrome default has changed to SameSite=Lax. Which means using this library without explicitly setting SameSite or secure will cause to have SameSite=None but not 'secure' which is not allowed by Chrome anymore.

I would expect SameSite not to be set if i don't set it explicitly through the API.

See also:
* Reject insecure SameSite=None cookies: 
https://www.chromestatus.com/feature/5633521622188032
* Cookies default to SameSite=Lax: 
https://www.chromestatus.com/feature/5088147346030592

**Comment by TINITUS** [comment]
https://blog.chromium.org/ Seems Chromium is temporary rolling back the SameSite changes.

**Comment by alienjedi** [comment]
This issue can be closed now because `ngx-cookie-service` now sets `Lax `by default and sets `Secure` to true when `None` is specified for the `SameSite` attribute and `Secure` is false.

**Comment by alienjedi** [comment]
> https://blog.chromium.org/ Seems Chromium is temporary rolling back the SameSite changes.

There is no mention of cookies or cross-site anything in the September update. I don't think it is rolling back

**Comment by robbiemu** [comment]
we are on 2.4.0.  I am noticing this bug in what I think is a pretty unusual way. We got the bug via UAT, for whom it seems to always occur that the cookie is not saved. I'm working with one who's  chrome version is Version 87.0.4280.141 (Official Build) (64-bit). For her it is not setting the cookie. For me, on version Version 87.0.4280.141 (Official Build) (x86_64) -- which is identical but mac instead of PC, it is working nearly all the time. One other dev on her build also noticed it is never working. But Our QA lead is also on that build of chrome, and for her, like me, it is always working. It gives me some small doubt that maybe this is not just the SameSite change  (or a really bad implementation of it was committed).

**Comment by robbiemu** [comment]
following up, this time on the correct thread!

I think that a solution to this problem would be to default to 'sameSite=Lax' like in the current version, or else to add 'secure' by default in addition to 'sameSite=None' which is already being added.

I stepped through and found that 2.4.0 source code compiles like this:
```js
            set(e, t, n, i, r, o, s="None") {
                if (!this.documentIsAccessible)
                    return;
                let a = encodeURIComponent(e) + "=" + encodeURIComponent(t) + ";";
                n && (a += "number" == typeof n ? "expires=" + new Date((new Date).getTime() + 1e3 * n * 60 * 60 * 24).toUTCString() + ";" : "expires=" + n.toUTCString() + ";"),
                i && (a += "path=" + i + ";"),
                r && (a += "domain=" + r + ";"),
                o && (a += "secure;"),
                this.document.cookie = a += "sameSite=" + s + ";"
            }
```

The structure of the compiled code is actually fine .. the 'None' is not!
Chrome's flags now include:

> SameSite by default cookies
> Treat cookies that don't specify a SameSite attribute as if they were SameSite=Lax. Sites must specify SameSite=None in order to enable third-party usage. – Mac, Windows, Linux, Chrome OS, Android
> 
> #same-site-by-default-cookies
> 
> Default
> Enable removing SameSite=None cookies
> Enables UI on chrome://settings/siteData to remove all third-party cookies and site data. – Mac, Windows, Linux, Chrome OS
> 
> #enable-removing-all-third-party-cookies
> 
> Default
> Cookies without SameSite must be secure
> If enabled, cookies without SameSite restrictions must also be Secure. If a cookie without SameSite restrictions is set without the Secure attribute, it will be rejected. This flag only has an effect if "SameSite by default cookies" is also enabled. – Mac, Windows, Linux, Chrome OS, Android
> 
> #cookies-without-same-site-must-be-secure
> 

_the first and last of which default to **true**._ This means that any third-party cookie can no longer be cross-site, specifically that the default settings in that function above will be rejected.

But this does bring up a couple of questions: why did it default to None? 
It is actually noted in the changelog. the reversion to Lax is not.
What was the 2.4 branch about? it is not in the changelog.
I don't see separate github branches here for the different releases, do you have to manually rerelease it?

And most importantly: Does anyone really need 2.x ? I mean did you upgrade the major number because it is actually incompatible? Because the easiest thing for everyone would be to just upgrade to the latest if that was available to them. Without a minor or even a major semver branch, I don't imagine it is too easy to release security patches and major bug patches, etc

**Comment by robbiemu** [comment]
Hi, please pardon the bother — What was the resolution or opinion in closing this ticket @stevermeister ?

**Comment by stevermeister** [comment]
@robbiemu thx for pointing out, it looks like it was closed by mistake. 
I did a big cleanup work and closed all the issues that were outdated

**Comment by stevermeister** [comment]
@axos88 @robbiemu 
I've created a simple example that works for me: 

https://github.com/stevermeister/ngx-cookie-service-base/blob/main/src/app/app.component.ts

stackblitz for it - https://stackblitz.com/github/stevermeister/ngx-cookie-service-base?file=src%2Fapp%2Fapp.component.ts

and pure app - https://rlmibppkj.github.stackblitz.io/


please, update the sandbox to highlight the issue

**Comment by asahu132** [comment]
> @axos88 @robbiemu
> I've created a simple example that works for me:
> 
> https://github.com/stevermeister/ngx-cookie-service-base/blob/main/src/app/app.component.ts
> 
> stackblitz for it - https://stackblitz.com/github/stevermeister/ngx-cookie-service-base?file=src%2Fapp%2Fapp.component.ts
> 
> and pure app - https://rlmibppkj.github.stackblitz.io/
> 
> please, update the sandbox to highlight the issue

it is not working for me on chrome version **91**

**Comment by michaelchadwick** [comment]
@asahu132 I can't get this code to work in any of the latest versions of the 3 major browsers:

- **Chrome** 91.0.4472.164 (Official Build) (x86_64)
- **Safari** 14.1.2 (15611.3.10.1.5, 15611)
- **Firefox** 90.0.1 (64-bit)

However, I _was_ able to get it to work once I used the proper `secure` and `sameSite` values in both Chrome and Firefox. Safari silently fails, though.

**Stackblitz**: [https://stackblitz.com/edit/github-ccirg8](https://stackblitz.com/edit/github-ccirg8?file=src/app/app.component.ts)

_Note_: there is a developer console warning in Firefox about the first cookie being "soon rejected": "Cookie 'testCookie0' will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute."

**Comment by pavankjadda** [comment]
> > @axos88 @robbiemu
> 
> > I've created a simple example that works for me:
> 
> > 
> 
> > https://github.com/stevermeister/ngx-cookie-service-base/blob/main/src/app/app.component.ts
> 
> > 
> 
> > stackblitz for it - https://stackblitz.com/github/stevermeister/ngx-cookie-service-base?file=src%2Fapp%2Fapp.component.ts
> 
> > 
> 
> > and pure app - https://rlmibppkj.github.stackblitz.io/
> 
> > 
> 
> > please, update the sandbox to highlight the issue
> 
> 
> 
> it is not working for me on chrome version **91**

It's working for me as expected. Would you mind sharing sample repo to reproduce the issue?

**Comment by pavankjadda** [comment]
> @asahu132 I can't get this code to work in any of the latest versions of the 3 major browsers:
> 
> 
> 
> - **Chrome** 91.0.4472.164 (Official Build) (x86_64)
> 
> - **Safari** 14.1.2 (15611.3.10.1.5, 15611)
> 
> - **Firefox** 90.0.1 (64-bit)
> 
> 
> 
> However, I _was_ able to get it to work once I used the proper `secure` and `sameSite` values in both Chrome and Firefox. Safari silently fails, though.
> 
> 
> 
> **Stackblitz**: [https://stackblitz.com/edit/github-ccirg8](https://stackblitz.com/edit/github-ccirg8?file=src/app/app.component.ts)
> 
> 
> 
> _Note_: there is a developer console warning in Firefox about the first cookie being "soon rejected": "Cookie 'testCookie0' will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute."

The library sets `SameSite=Lax` if not specified. 


As per the Mozilla docs and compatibility guide, this works in all browsers except IE. would you mind sharing StackBlitz example that reproduces your issue?

**Comment by pavankjadda** [comment]
@axos88 Please see my previous comment and let us know if you need any help further.

**Comment by pavankjadda** [comment]
See the [StackBlitz demo](https://stackblitz.com/edit/angular-ivy-1lrgdt?file=src%2Fapp%2Fapp.component.ts) and it works as expected. If this is a mistake or you still have the issue, please let us know.

**Comment by michaelchadwick** [comment]
@pavankjadda Thank you for the demo, and yes, it does work. However, it's using the latest version of `ng-cookie-service`, and at the time I was still using Angular 8, which required an older version (2.3). I updated to Angular 9 recently, and can report all is fine now with the latest version of `ngx-cookie-service`. Thank you!
